# Generated by Django 3.0.9 on 2020-09-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20200902_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='Branch',
        ),
    ]
