# Generated by Django 3.0.9 on 2020-09-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_auto_20200902_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculty'},
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Join_Date',
            field=models.DateField(null=True),
        ),
    ]
